<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:lf="http://www.impots.finances.gov.tn/liasse" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" targetNamespace="http://www.impots.finances.gov.tn/liasse" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xsd:include schemaLocation="Typescommuns.xsd"/>
	<xsd:include schemaLocation="Entete.xsd"/>
	<xsd:element name="F6303">
		<xsd:annotation>
			<xsd:documentation>Etat de résultat (OPCVM)</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="VersionDocument" type="xsd:string"/>
				<xsd:element name="Entete" type="lf:T_Entete"/>
				<xsd:element name="Details">
					<xsd:complexType>
						<xsd:all>
							<xsd:element name="F63030001" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>PR 1 - Revenus du portefeuille titres  (Net Exercice). "F63030002" + "F63030003" + "F63030004"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="PR 1 - Revenus du portefeuille titres  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63030002" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>a- Dividendes  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="a- Dividendes  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63030003" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>b - Revenus des obligations et valeurs assimilées  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="b - Revenus des obligations et valeurs assimilées  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63030004" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>c - Revenus des autres valeurs  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="c - Revenus des autres valeurs  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63030005" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>PR 2 - Revenus des placements monétaires  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="PR 2 - Revenus des placements monétaires  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63030006" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation> Total des revenus des placements (Net Exercice). "F63030001" + "F63030005"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default=" Total des revenus des placements (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63030007" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>CH 1 - Charges de gestion des placements  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="CH 1 - Charges de gestion des placements  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63030008" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Revenu net des placements (Net Exercice). "F63030006" - "F63030007"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Revenu net des placements (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63030009" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>PR 3 - Autres produits  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="PR 3 - Autres produits  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63030010" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>CH 2 - Autres charges  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="CH 2 - Autres charges  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63030011" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>résultat d'exploitation (Net Exercice). "F63030008" + "F63030009" - "F63030010"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="résultat d'exploitation (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63030012" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>PR 4 - Régularisation du résultat d'exploitation  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="PR 4 - Régularisation du résultat d'exploitation  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63030013" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Sommes distribuables de l'exercice (Net Exercice). "F63030011" + "F63030012"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Sommes distribuables de l'exercice (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63030014" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>PR 4 - Régularisation du résultat d'exploitation (annulation)  (Net Exercice). -"F63030012"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="PR 4 - Régularisation du résultat d'exploitation (annulation)  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63030015" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Variation des (+ou-) values potentielles sur titres  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Variation des (+ou-) values potentielles sur titres  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63030016" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>(+ou-) values réalisées sur cession des titres  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="(+ou-) values réalisées sur cession des titres  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63030017" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Frais de négociation  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Frais de négociation  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63030018" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>résultat net de l'exercice (Net Exercice). "F63030013" + "F63030014"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="résultat net de l'exercice (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63031001" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>PR 1 - Revenus du portefeuille titres  (Net Exercice - 1). "F63031002" + "F63031003" + "F63031004"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="PR 1 - Revenus du portefeuille titres  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63031002" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>a- Dividendes  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="a- Dividendes  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63031003" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>b - Revenus des obligations et valeurs assimilées  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="b - Revenus des obligations et valeurs assimilées  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63031004" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>c - Revenus des autres valeurs  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="c - Revenus des autres valeurs  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63031005" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>PR 2 - Revenus des placements monétaires  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="PR 2 - Revenus des placements monétaires  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63031006" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation> Total des revenus des placements (Net Exercice - 1). "F63031001" + "F63031005"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default=" Total des revenus des placements (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63031007" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>CH 1 - Charges de gestion des placements  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="CH 1 - Charges de gestion des placements  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63031008" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Revenu net des placements (Net Exercice - 1). "F63031006" - "F63031007"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Revenu net des placements (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63031009" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>PR 3 - Autres produits  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="PR 3 - Autres produits  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63031010" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>CH 2 - Autres charges  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="CH 2 - Autres charges  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63031011" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>résultat d'exploitation (Net Exercice - 1). "F63031008" + "F63031009" - "F63031010"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="résultat d'exploitation (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63031012" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>PR 4 - Régularisation du résultat d'exploitation  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="PR 4 - Régularisation du résultat d'exploitation  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63031013" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Sommes distribuables de l'exercice (Net Exercice - 1). "F63031011" + "F63031012"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Sommes distribuables de l'exercice (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63031014" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>PR 4 - Régularisation du résultat d'exploitation (annulation)  (Net Exercice - 1). -"F63031012"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="PR 4 - Régularisation du résultat d'exploitation (annulation)  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63031015" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Variation des (+ou-) values potentielles sur titres  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Variation des (+ou-) values potentielles sur titres  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63031016" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>(+ou-) values réalisées sur cession des titres  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="(+ou-) values réalisées sur cession des titres  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63031017" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Frais de négociation  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Frais de négociation  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63031018" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>résultat net de l'exercice (Net Exercice - 1). "F63031013" + "F63031014"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="résultat net de l'exercice (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:all>
						<xsd:assert test="lf:F63030001 = sum( ((lf:F63030002) , (lf:F63030003) , (lf:F63030004)))"/>
						<xsd:assert test="lf:F63030006 = sum( ((lf:F63030001) , (lf:F63030005)))"/>
						<xsd:assert test="lf:F63030008 = sum( ((lf:F63030006) , (-1)*(lf:F63030007)))"/>
						<xsd:assert test="lf:F63030011 = sum( ((lf:F63030008) , (lf:F63030009 ) , (-1)*(lf:F63030010)))"/>
						<xsd:assert test="lf:F63030013 = sum( ((lf:F63030011) , (lf:F63030012)))"/>
						<xsd:assert test="lf:F63030014 = sum( (( (-1)*(lf:F63030012) )))"/>
						<xsd:assert test="lf:F63030018 = sum( ((lf:F63030013) , (lf:F63030014) , (lf:F63030015) , (lf:F63030016) , (lf:F63030017)))"/>
						<xsd:assert test="lf:F63031001 = sum( ((lf:F63031002) , (lf:F63031003) , (lf:F63031004)))"/>
						<xsd:assert test="lf:F63031006 = sum( ((lf:F63031001) , (lf:F63031005)))"/>
						<xsd:assert test="lf:F63031008 = sum( ((lf:F63031006) , (-1)*(lf:F63031007)))"/>
						<xsd:assert test="lf:F63031011 = sum( ((lf:F63031008) , (lf:F63031009 )  , (-1)*(lf:F63031010)))"/>
						<xsd:assert test="lf:F63031013 = sum( ((lf:F63031011) , (lf:F63031012)))"/>
						<xsd:assert test="lf:F63031014 = sum( (((-1) * (lf:F63031012))))"/>
						<xsd:assert test="lf:F63031018 = sum( ((lf:F63031013) , (lf:F63031014) , (lf:F63031015) , (lf:F63031016) , (lf:F63031017)))"/>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>
