<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:lf="http://www.impots.finances.gov.tn/liasse" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" targetNamespace="http://www.impots.finances.gov.tn/liasse" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xsd:include schemaLocation="Typescommuns.xsd"/>
	<xsd:include schemaLocation="Entete.xsd"/>
	<xsd:element name="F6403">
		<xsd:annotation>
			<xsd:documentation>Etat de résultat (Associations - Micro crédits)</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="VersionDocument" type="xsd:string"/>
				<xsd:element name="Entete" type="lf:T_Entete"/>
				<xsd:element name="Details">
					<xsd:complexType>
						<xsd:all>
							<xsd:element name="F64030001" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>PR 1 - Apports (Net Exercice). "F64030002" + "F64030003" + "F64030004" + "F64030005" + "F64030006"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="PR 1 - Apports (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030002" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>a - Dons, legs et donations  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="a - Dons, legs et donations  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030003" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>b - Subventions  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="b - Subventions  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030004" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>c - Cotisations  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="c - Cotisations  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030005" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>d - Autres apports non affectés  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="d - Autres apports non affectés  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030006" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>e - Apports reportés imputés au résultat de l'exercice  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="e - Apports reportés imputés au résultat de l'exercice  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030007" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>PR 2 - Produits des placements  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="PR 2 - Produits des placements  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030008" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>PR 3 - Revenus des microcrédits  (Net Exercice). "F64030009" + "F64030010"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="PR 3 - Revenus des microcrédits  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030009" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>a - Intérêts et revenus assimilés  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="a - Intérêts et revenus assimilés  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030010" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>b - Autres revenus sur microcrédits  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="b - Autres revenus sur microcrédits  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030011" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>PR 4 - Reprise de provisions et récupération de créances passées en perte sur microcrédits  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="PR 4 - Reprise de provisions et récupération de créances passées en perte sur microcrédits  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030012" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>PR 5 - Autres produits d'exploitation  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="PR 5 - Autres produits d'exploitation  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030013" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>PR 6 - Gains  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="PR 6 - Gains  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030014" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Produits (Net Exercice). "F64030001" + "F64030007" + "F64030008" + "F64030011" + "F64030012" + "F64030013"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Produits (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030015" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>CH 1- Dons, subventions et services fournis  (Net Exercice). "F64030016" + "F64030017"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="CH 1- Dons, subventions et services fournis  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030016" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>a - Dons et subventions accordés  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="a - Dons et subventions accordés  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030017" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>b - Prestations de services fournies  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="b - Prestations de services fournies  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030018" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>CH 2 - Charges financières  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="CH 2 - Charges financières  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030019" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>CH 3 - Charges d'encadrement et de formation  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="CH 3 - Charges d'encadrement et de formation  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030020" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>CH 4- Dotations aux provisions et créances passées en pertes sur microcrédits  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="CH 4- Dotations aux provisions et créances passées en pertes sur microcrédits  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030021" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>CH 5 - Charges du personnel  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="CH 5 - Charges du personnel  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030022" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>CH 6 - Charges générales d'exploitation  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="CH 6 - Charges générales d'exploitation  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030023" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>CH 7 - Autres charges d'exploitation  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="CH 7 - Autres charges d'exploitation  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030024" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>CH 8 - Dotations aux amortissements et aux provisions sur immobilisations  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="CH 8 - Dotations aux amortissements et aux provisions sur immobilisations  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030025" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>CH 9 - Pertes  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="CH 9 - Pertes  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030026" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Total charges (Net Exercice). "F64030015" + ""F64030018" + "F64030019" + "F64030020" + "F64030021" + "F64030022" + "F64030023" + "F64030024" + "F64030025"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Total charges (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64030027" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Excedent (déficit) des produits sur les charges (Net Exercice). "F64030014" - "F64030026"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Excedent (déficit) des produits sur les charges (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031001" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>PR 1 - Apports (Net Exercice - 1). "F64031002" + "F64031003" + "F64031004" + "F64031005" + "F64031006"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="PR 1 - Apports (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031002" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>a - Dons, legs et donations  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="a - Dons, legs et donations  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031003" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>b - Subventions  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="b - Subventions  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031004" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>c - Cotisations  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="c - Cotisations  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031005" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>d - Autres apports non affectés  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="d - Autres apports non affectés  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031006" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>e - Apports reportés imputés au résultat de l'exercice  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="e - Apports reportés imputés au résultat de l'exercice  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031007" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>PR 2 - Produits des placements  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="PR 2 - Produits des placements  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031008" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>PR 3 - Revenus des microcrédits  (Net Exercice - 1). "F64031009" + "F64031010"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="PR 3 - Revenus des microcrédits  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031009" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>a - Intérêts et revenus assimilés  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="a - Intérêts et revenus assimilés  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031010" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>b - Autres revenus sur microcrédits  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="b - Autres revenus sur microcrédits  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031011" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>PR 4 - Reprise de provisions et récupération de créances passées en perte sur microcrédits  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="PR 4 - Reprise de provisions et récupération de créances passées en perte sur microcrédits  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031012" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>PR 5 - Autres produits d'exploitation  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="PR 5 - Autres produits d'exploitation  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031013" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>PR 6 - Gains  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="PR 6 - Gains  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031014" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Produits (Net Exercice - 1). "F64031001" + "F64031007" + "F64031008" + "F64031011" + "F64031012" + "F64031013"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Produits (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031015" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>CH 1- Dons, subventions et services fournis  (Net Exercice - 1). "F64031016" + "F64031017"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="CH 1- Dons, subventions et services fournis  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031016" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>a - Dons et subventions accordés  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="a - Dons et subventions accordés  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031017" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>b - Prestations de services fournies  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="b - Prestations de services fournies  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031018" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>CH 2 - Charges financières  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="CH 2 - Charges financières  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031019" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>CH 3 - Charges d'encadrement et de formation  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="CH 3 - Charges d'encadrement et de formation  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031020" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>CH 4- Dotations aux provisions et créances passées en pertes sur microcrédits  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="CH 4- Dotations aux provisions et créances passées en pertes sur microcrédits  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031021" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>CH 5 - Charges du personnel  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="CH 5 - Charges du personnel  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031022" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>CH 6 - Charges générales d'exploitation  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="CH 6 - Charges générales d'exploitation  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031023" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>CH 7 - Autres charges d'exploitation  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="CH 7 - Autres charges d'exploitation  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031024" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>CH 8 - Dotations aux amortissements et aux provisions sur immobilisations  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="CH 8 - Dotations aux amortissements et aux provisions sur immobilisations  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031025" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>CH 9 - Pertes  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="CH 9 - Pertes  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031026" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Total charges (Net Exercice - 1). "F64031015" + ""F64031018" + "F64031019" + "F64031020" + "F64031021" + "F64031022" + "F64031023" + "F64031024" + "F64031025"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Total charges (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F64031027" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Excedent (déficit) des produits sur les charges (Net Exercice - 1). "F64031014" - "F64031026"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Excedent (déficit) des produits sur les charges (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:all>
						<xsd:assert test="lf:F64030001 = sum( ((lf:F64030002) , (lf:F64030003) , (lf:F64030004) , (lf:F64030005) , (lf:F64030006)))"/>
						<xsd:assert test="lf:F64030008 = sum( ((lf:F64030009) , (lf:F64030010)))"/>
						<xsd:assert test="lf:F64030014 = sum( ((lf:F64030001) , (lf:F64030007) , (lf:F64030008) , (lf:F64030011) , (lf:F64030012) , (lf:F64030013)))"/>
						<xsd:assert test="lf:F64030015 = sum( ((lf:F64030016) , (lf:F64030017)))"/>
						<xsd:assert test="lf:F64030026 = sum( ((lf:F64030015) , (lf:F64030018) , (lf:F64030019) , (lf:F64030020) , (lf:F64030021) , (lf:F64030022) , (lf:F64030023) , (lf:F64030024) , (lf:F64030025)))"/>
						<xsd:assert test="lf:F64030027 = sum( ((lf:F64030014) , (-1)*(lf:F64030026)))"/>
						<xsd:assert test="lf:F64031001 = sum( ((lf:F64031002) , (lf:F64031003) , (lf:F64031004) , (lf:F64031005) , (lf:F64031006)))"/>
						<xsd:assert test="lf:F64031008 = sum( ((lf:F64031009) , (lf:F64031010)))"/>
						<xsd:assert test="lf:F64031014 = sum( ((lf:F64031001) , (lf:F64031007) , (lf:F64031008) , (lf:F64031011) , (lf:F64031012) , (lf:F64031013)))"/>
						<xsd:assert test="lf:F64031015 = sum( ((lf:F64031016) , (lf:F64031017)))"/>
						<xsd:assert test="lf:F64031026 = sum( ((lf:F64031015) , (lf:F64031018) , (lf:F64031019) , (lf:F64031020) , (lf:F64031021) , (lf:F64031022) , (lf:F64031023) , (lf:F64031024) , (lf:F64031025)))"/>
						<xsd:assert test="lf:F64031027 = sum( ((lf:F64031014) , (-1)*(lf:F64031026)))"/>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>
