// <auto-generated />
using System;
using LiasseFiscale.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LiasseFiscale.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContribuableUser", b =>
                {
                    b.Property<int>("ContribuablesId")
                        .HasColumnType("integer");

                    b.Property<int>("UtilisateursId")
                        .HasColumnType("integer");

                    b.HasKey("ContribuablesId", "UtilisateursId");

                    b.HasIndex("UtilisateursId");

                    b.ToTable("UserContribuables", (string)null);
                });

            modelBuilder.Entity("LiasseFiscale.Api.Models.Contribuable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CleMatriculeFiscal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeCategorie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeTva")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomOuRaisonSociale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroMatriculeFiscal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NumeroMatriculeFiscal", "CleMatriculeFiscal")
                        .IsUnique();

                    b.ToTable("Contribuables");
                });

            modelBuilder.Entity("LiasseFiscale.Api.Models.Deposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDepot")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LiasseId")
                        .HasColumnType("integer");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SignatureElectronique")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LiasseId")
                        .IsUnique();

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Deposits");
                });

            modelBuilder.Entity("LiasseFiscale.Api.Models.DocumentFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CheminStockage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeDocument")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstObligatoire")
                        .HasColumnType("boolean");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LiasseId")
                        .HasColumnType("integer");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LiasseId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("LiasseFiscale.Api.Models.Liasse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActeDeDepot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContribuableId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateClotureExercice")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateDebutExercice")
                        .HasColumnType("date");

                    b.Property<int>("Exercice")
                        .HasColumnType("integer");

                    b.Property<string>("ModeleF6004Choisi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeDepot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContribuableId", "Exercice");

                    b.ToTable("Liasses");
                });

            modelBuilder.Entity("LiasseFiscale.Api.Models.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateGeneration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepositId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepositId")
                        .IsUnique();

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("LiasseFiscale.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LiasseFiscale.Api.Models.ValidationError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Champ")
                        .HasColumnType("text");

                    b.Property<int>("DocumentFiscalId")
                        .HasColumnType("integer");

                    b.Property<int?>("Ligne")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentFiscalId");

                    b.ToTable("ValidationErrors");
                });

            modelBuilder.Entity("ContribuableUser", b =>
                {
                    b.HasOne("LiasseFiscale.Api.Models.Contribuable", null)
                        .WithMany()
                        .HasForeignKey("ContribuablesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiasseFiscale.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UtilisateursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LiasseFiscale.Api.Models.Deposit", b =>
                {
                    b.HasOne("LiasseFiscale.Api.Models.Liasse", "Liasse")
                        .WithOne("Deposit")
                        .HasForeignKey("LiasseFiscale.Api.Models.Deposit", "LiasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liasse");
                });

            modelBuilder.Entity("LiasseFiscale.Api.Models.DocumentFiscal", b =>
                {
                    b.HasOne("LiasseFiscale.Api.Models.Liasse", "Liasse")
                        .WithMany("Documents")
                        .HasForeignKey("LiasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liasse");
                });

            modelBuilder.Entity("LiasseFiscale.Api.Models.Liasse", b =>
                {
                    b.HasOne("LiasseFiscale.Api.Models.Contribuable", "Contribuable")
                        .WithMany("Liasses")
                        .HasForeignKey("ContribuableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contribuable");
                });

            modelBuilder.Entity("LiasseFiscale.Api.Models.Receipt", b =>
                {
                    b.HasOne("LiasseFiscale.Api.Models.Deposit", "Deposit")
                        .WithOne("Receipt")
                        .HasForeignKey("LiasseFiscale.Api.Models.Receipt", "DepositId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deposit");
                });

            modelBuilder.Entity("LiasseFiscale.Api.Models.ValidationError", b =>
                {
                    b.HasOne("LiasseFiscale.Api.Models.DocumentFiscal", "DocumentFiscal")
                        .WithMany("Erreurs")
                        .HasForeignKey("DocumentFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentFiscal");
                });

            modelBuilder.Entity("LiasseFiscale.Api.Models.Contribuable", b =>
                {
                    b.Navigation("Liasses");
                });

            modelBuilder.Entity("LiasseFiscale.Api.Models.Deposit", b =>
                {
                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("LiasseFiscale.Api.Models.DocumentFiscal", b =>
                {
                    b.Navigation("Erreurs");
                });

            modelBuilder.Entity("LiasseFiscale.Api.Models.Liasse", b =>
                {
                    b.Navigation("Deposit");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
