<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:lf="http://www.impots.finances.gov.tn/liasse" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" targetNamespace="http://www.impots.finances.gov.tn/liasse" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
  <xsd:simpleType name="T_NumMatriculeFiscal">
    <xsd:annotation>
      <xsd:documentation>Numero matricule fiscal</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:length value="7" />
      <xsd:whiteSpace value="collapse" />
      <xsd:pattern value="[0-9]{7}" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_CleMatriculeFiscal">
    <xsd:annotation>
      <xsd:documentation>Clé matricule fiscal</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:length value="1" />
      <xsd:pattern value="[ABCDEFGHJKLMNPQRSTVWXYZ]" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_CodeCategorie">
    <xsd:annotation>
      <xsd:documentation>Code categorie</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:length value="1" />
      <xsd:enumeration value="C" />
      <xsd:enumeration value="M" />
      <xsd:enumeration value="N" />
      <xsd:enumeration value="P" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_CodeTva">
    <xsd:annotation>
      <xsd:documentation>Code TVA</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:length value="1" />
      <xsd:enumeration value="A" />
      <xsd:enumeration value="B" />
      <xsd:enumeration value="D" />
      <xsd:enumeration value="P" />
      <xsd:enumeration value="N" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_MatriculeFiscal_13c">
    <xsd:annotation>
      <xsd:documentation>Matricule fiscal de structure : MAT-CLE-TVA-CAT-ETB</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:token">
      <xsd:pattern value="[0-9]{7}[ABCDEFGHJKLMNPQRSTVWXYZ][ABDNP][CMNP][0]{3}" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_Annee">
    <xsd:annotation>
      <xsd:documentation>Année</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:gYear" />
  </xsd:simpleType>
  <xsd:simpleType name="T_TypeIdentifiantContribuable">
    <xsd:annotation>
      <xsd:documentation>Type identifiant contribuable</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:length value="1" />
      <xsd:enumeration value="1">
        <xsd:annotation>
          <xsd:documentation>Matricule fiscal</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
      <xsd:enumeration value="2">
        <xsd:annotation>
          <xsd:documentation>CIN</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
      <xsd:enumeration value="3">
        <xsd:annotation>
          <xsd:documentation>Carte de sejour</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
      <xsd:enumeration value="4">
        <xsd:annotation>
          <xsd:documentation>Autre identifiant</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_ChaineTexte250">
    <xsd:annotation>
      <xsd:documentation>Chaine de 250 caracteres au maximum</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:maxLength value="250" />
      <xsd:whiteSpace value="collapse" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_Date">
    <xsd:annotation>
      <xsd:documentation>Date au format dd/mm/yyyy (Les années sont comprises entre 1900 et 2099)</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:token">
      <xsd:pattern value="((31/(0[13578]|1[02])/((19|20)\d{2}))|((0[1-9]|[12]\d|30)/(0[13456789]|1[012])/((19|20)\d{2}))|((0[1-9]|1\d|2[0-8])/02/((19|20)\d{2}))|(29/02/(19|20)((0[048]|[2468][048]|[13579][26]))))" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_ActeDeDepot">
    <xsd:annotation>
      <xsd:documentation>Actes de dépôts</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:token">
      <xsd:minLength value="1" />
      <xsd:maxLength value="1" />
      <xsd:enumeration value="0" />
      <xsd:enumeration value="1" />
      <xsd:enumeration value="2" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_NatureDepot">
    <xsd:annotation>
      <xsd:documentation>Nature dépôt : Definitif ou Provisoire</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:token">
      <xsd:minLength value="1" />
      <xsd:maxLength value="1" />
      <xsd:enumeration value="D" />
      <xsd:enumeration value="P" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_ModeleLiasse">
    <xsd:annotation>
      <xsd:documentation>Modele liasse fiscale</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:length value="1" />
      <xsd:enumeration value="G">
        <xsd:annotation>
          <xsd:documentation>Cas general</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
      <xsd:enumeration value="B">
        <xsd:annotation>
          <xsd:documentation>Banques</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
      <xsd:enumeration value="A">
        <xsd:annotation>
          <xsd:documentation>Assurances et réassurances</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
      <xsd:enumeration value="C">
        <xsd:annotation>
          <xsd:documentation>Associations, micro-credits</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
      <xsd:enumeration value="O">
        <xsd:annotation>
          <xsd:documentation>OPCVM</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_NombrePositif13">
    <xsd:annotation>
      <xsd:documentation>Nombre positif obligatoire de 13 caractères au maximum, sans partie decimale (0, 1, 2, ...)</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:nonNegativeInteger">
      <xsd:totalDigits value="13" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_NombrePositif15">
    <xsd:annotation>
      <xsd:documentation>Nombre positif obligatoire de 15 caractères au maximum, sans partie decimale (0, 1, 2, ...)</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:nonNegativeInteger">
      <xsd:totalDigits value="15" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_NombreNegatif13">
    <xsd:annotation>
      <xsd:documentation>Nombre negatif obligatoire de 13 caractères au maximum, sans partie decimale (..., -2, -1, 0)</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:nonPositiveInteger">
      <xsd:totalDigits value="13" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_NombreNegatif15">
    <xsd:annotation>
      <xsd:documentation>Nombre negatif obligatoire de 15 caractères au maximum, sans partie decimale (..., -2, -1, 0)</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:nonPositiveInteger">
      <xsd:totalDigits value="15" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_Nombre13">
    <xsd:annotation>
      <xsd:documentation>Nombre (Montant) obligatoire de 13 caractères au maximum, sans partie décimale et qui peut etre negatif</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:integer">
      <xsd:totalDigits value="13" />
      <xsd:fractionDigits value="0" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_Nombre15">
    <xsd:annotation>
      <xsd:documentation>Nombre (Montant) obligatoire de 13 caractères au maximum, sans partie décimale et qui peut etre negatif</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:integer">
      <xsd:totalDigits value="15" />
      <xsd:fractionDigits value="0" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_NombrePositifSM">
    <xsd:annotation>
      <xsd:documentation>Nombre positif obligatoire de 13 caractères au maximum, sans partie decimale (0, 1, 2, ...)</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:nonNegativeInteger">
      <xsd:totalDigits value="13" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_NombreNegatifSM">
    <xsd:annotation>
      <xsd:documentation>Nombre negatif obligatoire de 13 caractères au maximum, sans partie decimale (..., -2, -1, 0)</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:nonPositiveInteger">
      <xsd:totalDigits value="13" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_NombreSM">
    <xsd:annotation>
      <xsd:documentation>Nombre (Montant) obligatoire de 13 caractères au maximum, sans partie décimale et qui peut etre negatif</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:integer">
      <xsd:totalDigits value="13" />
      <xsd:fractionDigits value="0" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_NombrePositifMD">
    <xsd:annotation>
      <xsd:documentation>Nombre positif obligatoire de 13 caractères au maximum, sans partie decimale (0, 1, 2, ...)</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:nonNegativeInteger">
      <xsd:totalDigits value="15" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_NombreNegatifMD">
    <xsd:annotation>
      <xsd:documentation>Nombre negatif obligatoire de 13 caractères au maximum, sans partie decimale (..., -2, -1, 0)</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:nonPositiveInteger">
      <xsd:totalDigits value="15" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_NombreMD">
    <xsd:annotation>
      <xsd:documentation>Nombre (Montant) obligatoire de 13 caractères au maximum, sans partie décimale et qui peut etre negatif</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:integer">
      <xsd:totalDigits value="15" />
      <xsd:fractionDigits value="0" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_NombrePositifLG">
    <xsd:annotation>
      <xsd:documentation>Nombre positif obligatoire de 13 caractères au maximum, sans partie decimale (0, 1, 2, ...)</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:nonNegativeInteger">
      <xsd:totalDigits value="20" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_NombreNegatifLG">
    <xsd:annotation>
      <xsd:documentation>Nombre negatif obligatoire de 13 caractères au maximum, sans partie decimale (..., -2, -1, 0)</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:nonPositiveInteger">
      <xsd:totalDigits value="20" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_NombreLG">
    <xsd:annotation>
      <xsd:documentation>Nombre (Montant) obligatoire de 13 caractères au maximum, sans partie décimale et qui peut etre negatif</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:integer">
      <xsd:totalDigits value="20" />
      <xsd:fractionDigits value="0" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_NombrePositifXL">
    <xsd:annotation>
      <xsd:documentation>Nombre positif obligatoire de 13 caractères au maximum, sans partie decimale (0, 1, 2, ...)</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:nonNegativeInteger">
      <xsd:totalDigits value="25" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_NombreNegatifXL">
    <xsd:annotation>
      <xsd:documentation>Nombre negatif obligatoire de 13 caractères au maximum, sans partie decimale (..., -2, -1, 0)</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:nonPositiveInteger">
      <xsd:totalDigits value="25" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_NombreXL">
    <xsd:annotation>
      <xsd:documentation>Nombre (Montant) obligatoire de 13 caractères au maximum, sans partie décimale et qui peut etre negatif</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:integer">
      <xsd:totalDigits value="25" />
      <xsd:fractionDigits value="0" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_Taux52">
    <xsd:annotation>
      <xsd:documentation>Taux de 5 chiffres avec 2 positions décimale</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:decimal">
      <xsd:totalDigits value="5" />
      <xsd:fractionDigits value="2" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_Taux63">
    <xsd:annotation>
      <xsd:documentation>Taux de 6 chiffres avec 3 positions décimale</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:decimal">
      <xsd:totalDigits value="6" />
      <xsd:fractionDigits value="3" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_BeneficePerte">
    <xsd:annotation>
      <xsd:documentation>Nature resultat : Benefice (B) ou Perte (P)</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:length value="1" />
      <xsd:enumeration value="B" />
      <xsd:enumeration value="P" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="T_CodeTableau">
    <xsd:annotation>
      <xsd:documentation>Codification des tableaux de la liasse fiscale</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:length value="5" />
      <xsd:enumeration value="F6001">
        <xsd:annotation>
          <xsd:documentation>Bilan - Actifs (Cas general)</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
      <xsd:enumeration value="F6002">
        <xsd:annotation>
          <xsd:documentation>Bilan - Passifs (Cas general)</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
      <xsd:enumeration value="F6003">
        <xsd:annotation>
          <xsd:documentation>Etat de resultats (Cas general)</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
      <xsd:enumeration value="F6004">
        <xsd:annotation>
          <xsd:documentation>Etat de flux de tresorerie (Cas general)</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
      <xsd:enumeration value="F6005">
        <xsd:annotation>
          <xsd:documentation>Tableau de determination du resultat fiscal à partir du resultat comptable</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
      <xsd:enumeration value="F6006">
        <xsd:annotation>
          <xsd:documentation>Notes, principes comptables appliqués</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
      <xsd:enumeration value="F6007">
        <xsd:annotation>
          <xsd:documentation>Faits marquants de l'exercice</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
      <xsd:enumeration value="F6008">
        <xsd:annotation>
          <xsd:documentation>Schema des soldes intermediaires de gestion</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
      <xsd:enumeration value="F6009">
        <xsd:annotation>
          <xsd:documentation>Autres feuillets - Liasse - Notes aux états financiers</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
      <xsd:enumeration value="F6101" />
      <xsd:enumeration value="F6103" />
      <xsd:enumeration value="F6104" />
      <xsd:enumeration value="F6105" />
      <xsd:enumeration value="F6201" />
      <xsd:enumeration value="F6202" />
      <xsd:enumeration value="F6203" />
      <xsd:enumeration value="F6204" />
      <xsd:enumeration value="F6205" />
      <xsd:enumeration value="F6206" />
      <xsd:enumeration value="F6207" />
      <xsd:enumeration value="F6301" />
      <xsd:enumeration value="F6303" />
      <xsd:enumeration value="F6304" />
      <xsd:enumeration value="F6401" />
      <xsd:enumeration value="F6403" />
      <xsd:enumeration value="F6404" />
      <xsd:enumeration value="G7002" />
      <xsd:enumeration value="G7003" />
      <xsd:enumeration value="G7004" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="T_Entete">
    <xsd:annotation>
      <xsd:documentation>Entête d'une déclaration</xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="MatriculeFiscalDeclarant" type="lf:T_MatriculeFiscal_13c" />
      <xsd:element name="NometPrenomouRaisonSociale" type="lf:T_ChaineTexte250" />
      <xsd:element name="Activite" type="lf:T_ChaineTexte250" />
      <xsd:element name="Adresse" type="lf:T_ChaineTexte250" />
      <xsd:element name="Exercice" type="lf:T_Annee" />
      <xsd:element name="DateDebutExercice" type="lf:T_Date" />
      <xsd:element name="DateClotureExercice" type="lf:T_Date" />
      <xsd:element name="ActeDeDepot" type="lf:T_ActeDeDepot" default="0" />
      <xsd:element name="NatureDepot" type="lf:T_NatureDepot" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="F6301">
    <xsd:annotation>
      <xsd:documentation>Bilan-actifs-passifs (OPCVM)</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="VersionDocument" type="xsd:string" />
        <xsd:element name="Entete" type="lf:T_Entete" />
        <xsd:element name="Details">
          <xsd:complexType>
            <xsd:all>
              <xsd:element name="F63010001" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>AC 1 - Portefeuille titres (Net Exercice). "F63010002" + "F63010003" + "F63010004"</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="AC 1 - Portefeuille titres (Net Exercice)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63010002" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>a - Actions, valeurs assimilées et droits rattachés  (Net Exercice)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="a - Actions, valeurs assimilées et droits rattachés  (Net Exercice)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63010003" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>b - Obligations et valeurs assimilées  (Net Exercice)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="b - Obligations et valeurs assimilées  (Net Exercice)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63010004" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>c - Autres valeurs  (Net Exercice)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="c - Autres valeurs  (Net Exercice)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63010005" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>AC 2 - Placements monétaires et disponibilités  (Net Exercice). "F63010006" + "F63010007"</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="AC 2 - Placements monétaires et disponibilités  (Net Exercice)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63010006" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>a - Placements monétaires  (Net Exercice)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="a - Placements monétaires  (Net Exercice)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63010007" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>b - disponibilités  (Net Exercice)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="b - disponibilités  (Net Exercice)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63010008" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>AC 3 - Créances d'exploitation  (Net Exercice)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="AC 3 - Créances d'exploitation  (Net Exercice)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63010009" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>AC 4 - Autres actifs  (Net Exercice)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="AC 4 - Autres actifs  (Net Exercice)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63010010" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>Total actif (Net Exercice). "F63010001" + "F63010005" + "F63010008" + "F63010009"</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="Total actif (Net Exercice)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63010011" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>PA 1 - Opérateurs créditeurs  (Net Exercice)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="PA 1 - Opérateurs créditeurs  (Net Exercice)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63010012" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>PA 2 - Autres créditeurs divers  (Net Exercice)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="PA 2 - Autres créditeurs divers  (Net Exercice)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63010013" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>Total passif (Net Exercice). "F63010011" + "F63010012"</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="Total passif (Net Exercice)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63010014" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>CP 1 - Capital  (Net Exercice)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="CP 1 - Capital  (Net Exercice)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63010015" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>CP 2 - Sommes distribuables  (Net Exercice). "F63010016" + "F63010017"</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="CP 2 - Sommes distribuables  (Net Exercice)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63010016" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>a - Sommes distribuables des exercices antérieurs  (Net Exercice)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="a - Sommes distribuables des exercices antérieurs  (Net Exercice)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63010017" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>b- Sommes distribuables de l'exercice  (Net Exercice)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="b- Sommes distribuables de l'exercice  (Net Exercice)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63010018" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>Total actif net (Net Exercice). "F63010014" + "F63010015"</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="Total actif net (Net Exercice)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63010019" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>Total passif et actif net (Net Exercice). "F63010013" + "F63010018"</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="Total passif et actif net (Net Exercice)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63011001" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>AC 1 - Portefeuille titres (Net Exercice - 1). "F63011002" + "F63011003" + "F63011004"</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="AC 1 - Portefeuille titres (Net Exercice - 1)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63011002" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>a - Actions, valeurs assimilées et droits rattachés  (Net Exercice - 1)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="a - Actions, valeurs assimilées et droits rattachés  (Net Exercice - 1)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63011003" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>b - Obligations et valeurs assimilées  (Net Exercice - 1)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="b - Obligations et valeurs assimilées  (Net Exercice - 1)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63011004" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>c - Autres valeurs  (Net Exercice - 1)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="c - Autres valeurs  (Net Exercice - 1)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63011005" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>AC 2 - Placements monétaires et disponibilités  (Net Exercice - 1). "F63011006" + "F63011007"</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="AC 2 - Placements monétaires et disponibilités  (Net Exercice - 1)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63011006" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>a - Placements monétaires  (Net Exercice - 1)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="a - Placements monétaires  (Net Exercice - 1)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63011007" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>b - disponibilités  (Net Exercice - 1)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="b - disponibilités  (Net Exercice - 1)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63011008" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>AC 3 - Créances d'exploitation  (Net Exercice - 1)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="AC 3 - Créances d'exploitation  (Net Exercice - 1)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63011009" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>AC 4 - Autres actifs  (Net Exercice - 1)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="AC 4 - Autres actifs  (Net Exercice - 1)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63011010" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>Total actif (Net Exercice - 1). "F63011001" + "F63011005" + "F63011008" + "F63011009"</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="Total actif (Net Exercice - 1)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63011011" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>PA 1 - Opérateurs créditeurs  (Net Exercice - 1)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="PA 1 - Opérateurs créditeurs  (Net Exercice - 1)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63011012" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>PA 2 - Autres créditeurs divers  (Net Exercice - 1)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="PA 2 - Autres créditeurs divers  (Net Exercice - 1)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63011013" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>Total passif (Net Exercice - 1). "F63011011" + "F63011012"</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="Total passif (Net Exercice - 1)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63011014" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>CP 1 - Capital  (Net Exercice - 1)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="CP 1 - Capital  (Net Exercice - 1)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63011015" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>CP 2 - Sommes distribuables  (Net Exercice - 1). "F63011016" + "F63011017"</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="CP 2 - Sommes distribuables  (Net Exercice - 1)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63011016" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>a - Sommes distribuables des exercices antérieurs  (Net Exercice - 1)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="a - Sommes distribuables des exercices antérieurs  (Net Exercice - 1)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63011017" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>b- Sommes distribuables de l'exercice  (Net Exercice - 1)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="b- Sommes distribuables de l'exercice  (Net Exercice - 1)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63011018" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>Total actif net (Net Exercice - 1). "F63011014" + "F63011015"</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="Total actif net (Net Exercice - 1)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="F63011019" maxOccurs="1">
                <xsd:annotation>
                  <xsd:documentation>Total passif et actif net (Net Exercice - 1). "F63011013" + "F63011018"</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="lf:T_Nombre15">
                      <xsd:attribute name="Libelle" type="xsd:string" default="Total passif et actif net (Net Exercice - 1)" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
            </xsd:all>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>