<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:lf="http://www.impots.finances.gov.tn/liasse" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" targetNamespace="http://www.impots.finances.gov.tn/liasse" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xsd:include schemaLocation="Typescommuns.xsd"/>
	<xsd:include schemaLocation="Entete.xsd"/>
	<xsd:element name="F6004">
		<xsd:annotation>
			<xsd:documentation>Etat de flux de tresorerie-Modèle autorisé(Cas general)</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="VersionDocument" type="xsd:string"/>
				<xsd:element name="Entete" type="lf:T_Entete"/>
				<xsd:element name="Details">
					<xsd:complexType>
						<xsd:all>
							<xsd:element name="F60040001" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Flux de Trésorerie provenant de (affectés à) l'Exploitation  (Net Exercice) .F60040002+F60040003+F60040004+F60040005+F60040006+F60040007+F60040008+F60040009+F60040010</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Flux de Trésorerie provenant de (affectés à) l'Exploitation  (Net Exercice) "/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040002" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Résultat net (Net Exercice) F60030091</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Résultat net (Net Exercice) "/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040003" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Ajustement amortissement et provision (Net Exercice) F60030046</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Ajustement amortissement et provision (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040004" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Variation des stocks (Net Exercice) F60011037 - F60010037 </xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Variation des stocks (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040005" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Variation des créances (Net Exercice) F60011044-F60010044</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Variation des créances (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040006" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Variation des autres actifs (Net Exercice)F60011050-F60010050</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Variation des autres actifs (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040007" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Variation des fournisseurs et autres dettes (Net Exercice)F60020032+F60020038-F60021032-F60021038</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Variation des fournisseurs et autres dettes (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040008" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Ajustement plus au moins values de cession (Net Exercice)F60030073-F60030070</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Ajustement plus au moins values de cession (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040009" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Ajustement transfert des charges (Net Exercice)F60030019</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Ajustement transfert des charges (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040010" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Autres(Flux de trésorerie provenant de(affectés à) l'exploitation) (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Ajustement transfert des charges (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040011" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Flux de Trésorerie provenant de (affectés aux)  activités d'Investissement (Net Exercice)F60040012+F60040013+F60040014+F60040015+F60040016</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Flux de Trésorerie provenant de (affectés aux)  activités d'Investissement (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040012" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Décaissements provenant de l'acquisition d'immobilisations corporelles et incorporelles (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Décaissements provenant de l'acquisition d'immobilisations corporelles et incorporelles (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040013" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Encaissements provenant de l'acquisition d'immobilisations corporelles et incorporelles (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Encaissements provenant de l'acquisition d'immobilisations corporelles et incorporelles (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040014" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Décaissements provenant de l'acquisition d'immobilisations financières (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Décaissements provenant de l'acquisition d'immobilisations financières (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040015" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Encaissements provenant de l'acquisition d'immobilisations financières (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Encaissements provenant de l'acquisition d'immobilisations financières (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040016" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Autres(Flux de Trésorerie provenant de (affectés aux) activités d'investissement (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Encaissements provenant de l'acquisition d'immobilisations financières (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040017" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Flux de Trésorerie provenant des (affectés aux) activités de Financement (Net Exercice)F60040018+F60040019+F60040020+F60040021+F60040022</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Flux de Trésorerie provenant des (affectés aux) activités de Financement (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040018" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Encaissement suite à l'émission d'actions  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Encaissement suite à l'émission d'actions  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040019" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Dividendes et autres distribution (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Dividendes et autres distribution (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040020" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Encaissements provenant des emprunts (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Encaissements provenant des emprunts (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040021" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Remboursement d'emprunts (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Remboursement d'emprunts (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040022" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Autres (Flux de Trésorerie provenant des (affectés aux) activités de financement)(Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Remboursement d'emprunts (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040023" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Incidences des variations des taux de change/les liquidités équiv° (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Incidences des variations des taux de change/les liquidités  équiv° (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040024" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Autres Postes des Flux de Trésorerie (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Autres Postes des Flux de Trésorerie (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040025" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Variation de Trésorerie (Net Exercice) F60040024+F60040023+F60040017+F60040011+F60040001</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Variation de Trésorerie (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040026" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Trésorerie au début de l'exercice (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Trésorerie au début de l'exercice (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60040027" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Trésorerie à la clôture de l'exercice (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Trésorerie à la clôture de l'exercice (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041001" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Flux de Trésorerie provenant de (affectés à) l'Exploitation  (Net Exercice - 1) .F60041002+F60041003+F60041004+F60041005+F60041006+F60041007+F60041008+F60041009+F60041010</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Flux de Trésorerie provenant de (affectés à) l'Exploitation  (Net Exercice - 1) "/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041002" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Résultat net (Net Exercice - 1) F60031091</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Résultat net (Net Exercice - 1) "/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041003" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Ajustement amortissement et provision (Net Exercice - 1) F60031046</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Ajustement amortissement et provision (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041004" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Variation des stocks (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Variation des stocks (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041005" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Variation des créances (Net Exercice - 1) </xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Variation des créances (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041006" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Variation des autres actifs (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Variation des autres actifs (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041007" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Variation des fournisseurs et autres dettes (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Variation des fournisseurs et autres dettes (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041008">
								<xsd:annotation>
									<xsd:documentation>Ajustement plus au moins values de cession (Net Exercice - 1) F60031073-F60031070</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Ajustement plus au moins values de cession (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041009" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Ajustement transfert des charges (Net Exercice - 1) F60031019</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Ajustement transfert des charges (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041010" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Autres (Flux de Trésorerie provenant de (affectés à) l'Exploitation )  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Ajustement transfert des charges (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041011">
								<xsd:annotation>
									<xsd:documentation>Flux de Trésorerie provenant de (affectés aux)  activités d'Investissement (Net Exercice - 1) F60041012+F60041013+F60041014+F60041015+F60041016</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Flux de Trésorerie provenant de (affectés aux)  activités d'Investissement (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041012" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Décaissements provenant de l'acquisition d'immobilisations corporelles et incorporelles (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Décaissements provenant de l'acquisition d'immobilisations corporelles et incorporelles (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041013" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Encaissements provenant de l'acquisition d'immobilisations corporelles et incorporelles (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Encaissements provenant de l'acquisition d'immobilisations corporelles et incorporelles (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041014" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Décaissements provenant de l'acquisition d'immobilisations financières (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Décaissements provenant de l'acquisition d'immobilisations financières (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041015" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Encaissements provenant de l'acquisition d'immobilisations financières (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Encaissements provenant de l'acquisition d'immobilisations financières (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041016" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Autres (Flux de Trésorerie provenant de (affectés aux)  activités d'Investissement) (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Encaissements provenant de l'acquisition d'immobilisations financières (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041017" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Flux de Trésorerie provenant des (affectés aux) activités de Financement (Net Exercice - 1) F60041016+F60041017+F60041018+F60041019</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Flux de Trésorerie provenant des (affectés aux) activités de Financement (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041018" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Encaissement suite à l'émission d'actions  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Encaissement suite à l'émission d'actions  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041019" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Dividendes et autres distribution (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Dividendes et autres distribution (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041020" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Encaissements provenant des emprunts (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_NombrePositif15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Encaissements provenant des emprunts (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041021" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Remboursement d'emprunts (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Remboursement d'emprunts (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041022" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Autres (Flux de Trésorerie provenant des (affectés aux) activités de Financement) (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Remboursement d'emprunts (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041023" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Incidences des variations des taux de change/les liquidités équiv° (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Incidences des variations des taux de change/les liquidités  équiv° (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041024" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Autres Postes des Flux de Trésorerie (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Autres Postes des Flux de Trésorerie (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041025" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Variation de Trésorerie (Net Exercice - 1) F60041024+F60041023+F60040017+F60041011+F60041001</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Variation de Trésorerie (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041026" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Trésorerie au début de l'exercice (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Trésorerie au début de l'exercice (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F60041027" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Trésorerie à la clôture de l'exercice (Net Exercice-1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Trésorerie à la clôture de l'exercice (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:all>
						<xsd:assert test="lf:F60040001 = sum( ((lf:F60040002) , (lf:F60040003) , (lf:F60040004) , (lf:F60040005) , (lf:F60040006) , (lf:F60040007) , (lf:F60040008) , (lf:F60040009) , (lf:F60040010 )))"/>
						<xsd:assert test="lf:F60040011 = sum( ((lf:F60040012) , (lf:F60040013) , (lf:F60040014) , (lf:F60040015) , (lf:F60040016 )))"/>
						<xsd:assert test="lf:F60040017 = sum( ((lf:F60040018) , (lf:F60040019) , (lf:F60040020) , (lf:F60040021) , (lf:F60040022 )))"/>
						<xsd:assert test="lf:F60040025 = sum( ((lf:F60040024) , (lf:F60040023) , (lf:F60040017) , (lf:F60040011) , (lf:F60040001 )))"/>
						<xsd:assert test="lf:F60040026 = sum( ((lf:F60041027)))"/>
						<xsd:assert test="lf:F60041001 = sum( ((lf:F60041002) , (lf:F60041003) , (lf:F60041004) , (lf:F60041005) , (lf:F60041006) , (lf:F60041007) , (lf:F60041008) , (lf:F60041009) , (lf:F60041010 )))"/>
						<xsd:assert test="lf:F60041011 = sum( ((lf:F60041012) , (lf:F60041013) , (lf:F60041014) , (lf:F60041015) , (lf:F60041016 )))"/>
						<xsd:assert test="lf:F60041017 = sum( ((lf:F60041018) , (lf:F60041019) , (lf:F60041020) , (lf:F60041021) , (lf:F60041022 )))"/>
						<xsd:assert test="lf:F60041025 = sum( ((lf:F60041024) , (lf:F60041023) , (lf:F60041017) , (lf:F60041011) , (lf:F60041001 )))"/>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>
