<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:lf="http://www.impots.finances.gov.tn/liasse" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" targetNamespace="http://www.impots.finances.gov.tn/liasse" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xsd:include schemaLocation="Typescommuns.xsd"/>
	<xsd:include schemaLocation="Entete.xsd"/>
	<xsd:element name="F6304">
		<xsd:annotation>
			<xsd:documentation>Etat de variation de l'actif net (OPCVM)</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="VersionDocument" type="xsd:string"/>
				<xsd:element name="Entete" type="lf:T_Entete"/>
				<xsd:element name="Details">
					<xsd:complexType>
						<xsd:all>
							<xsd:element name="F63040001" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Variation de l'actif net (Net Exercice). "F63040002" + "F63040007" + "F63040008"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Variation de l'actif net (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040002" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>AN1 - Variation de l'actif net (Résultant des operations d'exploitation) (Net Exercice). "F63040003" + "F63040004" + "F63040005" + "F63040006"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="AN1 - Variation de l'actif net (Résultant des operations d'exploitation) (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040003" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>a - Résultat d'exploitation  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="a - Résultat d'exploitation  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040004">
								<xsd:annotation>
									<xsd:documentation>b - Variation des (+ou-) values potentielles sur titres  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="b - Variation des (+ou-) values potentielles sur titres  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040005" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>c - (+ou-) values réalisées sur cession de titres  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="c - (+ou-) values réalisées sur cession de titres  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040006" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>d - Frais de négociation de titres  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="d - Frais de négociation de titres  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040007" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>AN 2 - Distribution des dividendes (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="AN 2 - Distribution des dividendes (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040008" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>AN 3 - Transactions sur le capital (Net Exercice). "F63040009" + "F63040014"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="AN 3 - Transactions sur le capital (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040009" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>a- Souscriptions  (Net Exercice). "F63040010" + "F63040011" + "F63040012" + "F63040013"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="a- Souscriptions  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040010" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Variation des plus (ou moins) values potentielles sur titres  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Variation des plus (ou moins) values potentielles sur titres  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040011">
								<xsd:annotation>
									<xsd:documentation>Plus (ou moins) values réalisées sur cession des titres  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Plus (ou moins) values réalisées sur cession des titres  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040012">
								<xsd:annotation>
									<xsd:documentation>Plus (ou moins) values réalisées sur cession des titres  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Plus (ou moins) values réalisées sur cession des titres  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040013" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Frais de négociation  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Frais de négociation  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040014" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>b- Rachats  (Net Exercice). "F63040015" + "F63040016" + "F63040017" + "F63040018"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="b- Rachats  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040015" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Capital  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Capital  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040016" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Régularisation des sommes non distribuables de l'exercice  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Régularisation des sommes non distribuables de l'exercice  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040017" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Régularisation des sommes distribuables  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Régularisation des sommes distribuables  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040018" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Droits de sortie  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Droits de sortie  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040019" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Valeur liquidative (Net Exercice). "F63040020" + "F63040023"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Valeur liquidative (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040020" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>AN 4 - Actif net (Net Exercice). "F63040021" + "F63040022"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="AN 4 - Actif net (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040021" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>a - en début d'exercice   (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="a - en début d'exercice   (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040022" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>b - en fin d'exercice  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="b - en fin d'exercice  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040023" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>AN 5 - Nombre d'actions (ou de parts)  (Net Exercice). "F63040024" + "F63040025"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="AN 5 - Nombre d'actions (ou de parts)  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040024" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>a - en début d'exercice   (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="a - en début d'exercice   (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040025" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>b - en fin d'exercice  (Net Exercice)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="b - en fin d'exercice  (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63040026" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>AN 6 - Taux de rendement annuel (Net Exercice). ("F63040019" + "F63041019") / "F63041019"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="AN 6 - Taux de rendement annuel (Net Exercice)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041001" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Variation de l'actif net (Net Exercice - 1). "F63041002" + "F63041007" + "F63041008"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Variation de l'actif net (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041002" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>AN1 - Variation de l'actif net (Résultant des operations d'exploitation) (Net Exercice - 1). "F63041003" + "F63041004" + "F63041005" + "F63041006"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="AN1 - Variation de l'actif net (Résultant des operations d'exploitation) (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041003" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>a - Résultat d'exploitation  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="a - Résultat d'exploitation  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041004">
								<xsd:annotation>
									<xsd:documentation>b - Variation des (+ou-) values potentielles sur titres  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="b - Variation des (+ou-) values potentielles sur titres  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041005">
								<xsd:annotation>
									<xsd:documentation>c - (+ou-) values réalisées sur cession de titres  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="c - (+ou-) values réalisées sur cession de titres  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041006" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>d - Frais de négociation de titres  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="d - Frais de négociation de titres  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041007" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>AN 2 - Distribution des dividendes (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="AN 2 - Distribution des dividendes (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041008" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>AN 3 - Transactions sur le capital (Net Exercice - 1). "F63041009" + "F63041014"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="AN 3 - Transactions sur le capital (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041009" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>a- Souscriptions  (Net Exercice - 1). "F63041010" + "F63041011" + "F63041012" + "F63041013"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="a- Souscriptions  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041010" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Variation des plus (ou moins) values potentielles sur titres  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Variation des plus (ou moins) values potentielles sur titres  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041011">
								<xsd:annotation>
									<xsd:documentation>Plus (ou moins) values réalisées sur cession des titres  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Plus (ou moins) values réalisées sur cession des titres  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041012">
								<xsd:annotation>
									<xsd:documentation>Plus (ou moins) values réalisées sur cession des titres  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Plus (ou moins) values réalisées sur cession des titres  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041013" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Frais de négociation  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Frais de négociation  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041014" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>b- Rachats  (Net Exercice - 1). "F63041015" + "F63041016" + "F63041017" + "F63041018"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="b- Rachats  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041015" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Capital  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Capital  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041016" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Régularisation des sommes non distribuables de l'exercice  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Régularisation des sommes non distribuables de l'exercice  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041017" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Régularisation des sommes distribuables  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Régularisation des sommes distribuables  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041018" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Droits de sortie  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Droits de sortie  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041019" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>Valeur liquidative (Net Exercice - 1). "F63041020" + "F63041023"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="Valeur liquidative (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041020" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>AN 4 - Actif net (Net Exercice - 1). "F63041021" + "F63041022"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="AN 4 - Actif net (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041021" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>a - en début d'exercice   (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="a - en début d'exercice   (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041022" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>b - en fin d'exercice  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="b - en fin d'exercice  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041023" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>AN 5 - Nombre d'actions (ou de parts)  (Net Exercice - 1). "F63041024" + "F63041025"</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="AN 5 - Nombre d'actions (ou de parts)  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041024" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>a - en début d'exercice   (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="a - en début d'exercice   (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041025" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>b - en fin d'exercice  (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="b - en fin d'exercice  (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="F63041026" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>AN 6 - Taux de rendement annuel (Net Exercice - 1)</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="lf:T_Nombre15">
											<xsd:attribute name="Libelle" type="xsd:string" default="AN 6 - Taux de rendement annuel (Net Exercice - 1)"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:all>
						<xsd:assert test="lf:F63040001 = sum( ((lf:F63040002) , (lf:F63040007) , (lf:F63040008)))"/>
						<xsd:assert test="lf:F63040002 = sum( ((lf:F63040003) , (lf:F63040004) , (lf:F63040005) , (lf:F63040006)))"/>
						<xsd:assert test="lf:F63040008 = sum( ((lf:F63040009) , (lf:F63040014)))"/>
						<xsd:assert test="lf:F63040009 = sum( ((lf:F63040010) , (lf:F63040011) , (lf:F63040012) , (lf:F63040013)))"/>
						<xsd:assert test="lf:F63040014 = sum( ((lf:F63040015) , (lf:F63040016) , (lf:F63040017) , (lf:F63040018)))"/>
						<xsd:assert test="lf:F63040020 = sum( ((lf:F63040022) , (-1)*(lf:F63040021)))"/>
						<xsd:assert test="lf:F63040023 = sum( ((lf:F63040025) , (-1)*(lf:F63040024)))"/>
						<!-- <xsd:assert test="lf:F63040026 = sum( ((lf:F63040019) , (lf:F63041019)) ) / (lf:F63041019)"/> -->						
						<xsd:assert test="lf:F63041001 = sum( ((lf:F63041002) , (lf:F63041007) , (lf:F63041008)))"/>
						<xsd:assert test="lf:F63041002 = sum( ((lf:F63041003) , (lf:F63041004) , (lf:F63041005) , (lf:F63041006)))"/>
						<xsd:assert test="lf:F63041008 = sum( ((lf:F63041009) , (lf:F63041014)))"/>
						<xsd:assert test="lf:F63041009 = sum( ((lf:F63041010) , (lf:F63041011) , (lf:F63041012) , (lf:F63041013)))"/>
						<xsd:assert test="lf:F63041014 = sum( ((lf:F63041015) , (lf:F63041016) , (lf:F63041017) , (lf:F63041018)))"/>
						<xsd:assert test="lf:F63041020 = sum( ((lf:F63041022) , (-1)*(lf:F63041021)))"/>
						<xsd:assert test="lf:F63041023 = sum( ((lf:F63041025) , (-1)*(lf:F63041024)))"/>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>
